org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

mod_gradle_script_version=1.0.55
enable_curseforge_upload=false
enable_modrinth_upload=false
enable_mod_update=false

mod_version=0.2.0
mod_id=notes
mod_display_name=Notes
mod_description=This mod adds notes
mod_authors=Kimiram

java_version=21
java_toolchain_version=21
use_shadow=false
maven_group=kimiram.notes
archives_base_name=notes

minecraft_version=1.20.4
minecraft_user_name_prefix=kimiram
random_minecraft_user_name=true

parchment_mappings=parchment-1.20.4:2024.04.14

fabric_loom_version=1.14-SNAPSHOT
fabric_loader_version=0.18.3
import_fabric_api=true
fabric_api_version=0.97.3+1.20.4

neoforge_version=20.4.251