org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

mod_gradle_script_version=1.0.6

mod_version=0.4.1
mod_id=notes
mod_description=This mod adds notes

minecraft_version=26.2

fabric_loom_version=1.15-SNAPSHOT
fabric_loader_version=0.18.5
fabric_api_version=0.154.0+26.2

neogradle_version=7.1.38
neoforge_version=26.2.0.7-beta

imagelib_version=0.0.5-26.2