modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="notes"
version="${mod_version}+${minecraft_version}"
displayName="Notes"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="assets/notes/icon.png"
authors="Kimiram"
description='''${mod_description}'''

[[dependencies.notes]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.notes]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"